code/flask webapp/app/models/__init__.py
from app.models.user import Users
from app.models.movie import Movies
from app.models.rating import Ratings

__all__ = ['Users', 'Movies', 'Ratings']

code/flask webapp/app/models/movie.py
from app.extensions import db

class Movies(db.Model):
    __tablename__ = "movies"
    movieId = db.Column(db.BigInteger, primary_key=True)
    title = db.Column(db.String(200), nullable=False)
    genres = db.Column(db.String(200), nullable=False)
    release_year = db.Column(db.Integer, nullable=False)

    def __repr__(self):
        return f"<Movies(movieId={self.movieId}, title={self.title}, genres={self.genres}>"

code/flask webapp/app/models/rating.py
from app.extensions import db

class Ratings(db.Model):
    id = db.Column(db.BigInteger, primary_key=True)
    userId = db.Column(db.BigInteger, nullable=False, index=True)
    movieId = db.Column(db.BigInteger, nullable=False, index=True)
    rating = db.Column(db.Float, nullable=False)

    def __repr__(self):
        return f"<Ratings(id={self.id}, userId={self.userId}, movieId={self.movieId}, rating={self.rating}>"

code/flask webapp/app/models/user.py
from app.extensions import db
from flask_login import UserMixin

class Users(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(200), nullable=False, unique=True)
    password = db.Column(db.String(200), nullable=False)

    def __repr__(self):
        return f"<Name {self.username}>"

code/flask webapp/app/forms/__init__.py
from app.forms.auth import LoginForm, RegisterForm

__all__ = ['LoginForm', 'RegisterForm']

code/flask webapp/app/forms/auth.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired

class RegisterForm(FlaskForm):
    username = StringField("Username", validators=[DataRequired()])
    password = PasswordField("Password", validators=[DataRequired()])
    submit = SubmitField("Register")

class LoginForm(FlaskForm):
    username = StringField("Username", validators=[DataRequired()])
    password = PasswordField("Password", validators=[DataRequired()])
    submit = SubmitField("Log-in")

code/flask webapp/app/__init__.py
import eventlet
eventlet.monkey_patch()

from flask import Flask
from app.config import Config
from app.extensions import init_extensions

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    with app.app_context():
        # Initialize extensions
        init_extensions(app)

        # Register blueprints
        from app.routes.auth import auth
        from app.routes.main import main
        from app.routes.movie import movie
        
        app.register_blueprint(auth)
        app.register_blueprint(main)
        app.register_blueprint(movie)

    return app

code/flask webapp/app/routes/__init__.py
from app.routes.auth import auth
from app.routes.main import main
from app.routes.movie import movie

__all__ = ['auth', 'main', 'movie']

code/flask webapp/app/routes/auth.py
from flask import Blueprint, render_template, redirect, url_for, flash
from flask_login import login_user, logout_user, login_required
from app.forms.auth import LoginForm, RegisterForm
from app.models.user import Users
from app.extensions import db
from werkzeug.security import generate_password_hash, check_password_hash

auth = Blueprint('auth', __name__)

@auth.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = Users.query.filter_by(username=form.username.data).first()
        if user and check_password_hash(user.password, form.password.data):
            login_user(user)
            return redirect(url_for("main.dashboard"))
        flash("Invalid credentials")
    return render_template("login.html", form=form)

@auth.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("auth.login"))

@auth.route("/register", methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    
    if form.validate_on_submit():
        # Check if the username already exists
        user = Users.query.filter_by(username=form.username.data).first()
        if user:
            flash("Username already exists. Please choose a different one.", "danger")
            # Don't redirect; render the template again with the form and error message
            return render_template("register.html", form=form, our_users=Users.query.all())
        else:
            # Hash the password
            hashed_password = generate_password_hash(form.password.data, method='sha256')

            # Create a new user with the hashed password
            new_user = Users(username=form.username.data, password=hashed_password)
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user)
            return redirect(url_for("main.dashboard", user=new_user))

    # Render the form with the current data if the user submits an invalid form
    return render_template("register.html", form=form, our_users=Users.query.all())

code/flask webapp/app/routes/main.py
from flask import Blueprint, render_template
from flask_login import login_required

main = Blueprint('main', __name__)

@main.route("/")
def home():
    return render_template("index.html")

@main.route("/dashboard")
@login_required
def dashboard():
    return render_template("dashboard.html")

code/flask webapp/app/routes/movie.py
from flask import Blueprint, render_template, request, redirect, url_for, current_app, jsonify
from flask_login import login_required, current_user
from app.services.movie_service import MovieService
from app.extensions import db
import threading
from scripts import get_all_ratings, retrain_svd_model

movie = Blueprint('movie', __name__)

@movie.route("/movies")
@login_required
async def movies():
    service = MovieService()
    query = request.args.get("query", "")
    moviename = request.args.get("moviename", "")
    page = request.args.get("p", "1")
    
    movies_list = await service.get_movies(query, moviename, page, current_user.id)
    query_info = {
        'query': query,
        'page_to_load': int(page) + 1
    }

    return render_template("movie.html", movies=movies_list, query_info=query_info)

@movie.route("/add_rating", methods=["POST"])
@login_required
def add_rating():
    service = MovieService()
    rating = float(request.form.get("rating"))
    movieId = request.form.get("movieId")
    query = request.form.get("query")
    moviename = request.form.get("moviename")
    page = request.form.get("p")
    
    service.add_or_update_rating(current_user.id, movieId, rating)
    return redirect(url_for('movie.start_task', query=query, moviename=moviename, page=page))

@movie.route("/search_movie", methods=["GET"])
@login_required
def search_movie():
    word = request.args.get("searchbar")
    return redirect(url_for("movie.movies", query="search", moviename=word))

task_status = {'done': False, 'redirect_url': None}

@movie.route('/start_task')
@login_required
def start_task():
    query = request.args.get('query')
    moviename = request.args.get('moviename', "")
    page = request.args.get('p', "1")
    
    # Reset task status
    task_status['done'] = False
    task_status['redirect_url'] = None
    
    # Start background task
    thread = threading.Thread(target=background_task, args=(query, moviename, page, current_app._get_current_object()))
    thread.start()
    
    return render_template('loading.html')

@movie.route('/check_task_status')
@login_required
def check_task_status():
    return jsonify(task_status)

def background_task(query, moviename, page, app):
    with app.app_context():
        ratings_df = get_all_ratings()
        retrain_svd_model(ratings_df)
        
        task_status['done'] = True
        task_status['redirect_url'] = f"/movies?query={query}&moviename={moviename}&p={page}"

code/flask webapp/app/services/__init__.py
from app.services.movie_service import MovieService

__all__ = ['MovieService']

code/flask webapp/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <title>What2Watch</title>
    <style>
      html, body {
          height: 100%;  /* Ensure the body takes up the full viewport height */
          display: flex;
          flex-direction: column; /* Stack the content vertically */
      }
      
      .footer {
          margin-top: auto; /* Pushes the footer to the bottom */
      }
    </style>
  </head>
  <body>
    {% include "navbar.html" %}
    <br>
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        <div class="container mt-3">
            {% for category, message in messages %}
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
        </div>
    {% endif %}
{% endwith %}
    <br />
    <div class="container">
      {% block content %}
      <h1>test</h1>
      {% endblock %}
    </div>
  
    <br>
    <br>
  
    <footer class="bg-dark text-white py-4 mt-auto">
      <div class="container text-center">
          <p class="mb-0">What2Watch </p>
          <div>Note all movies are up to 2022</div>
      </div>
  </footer>

  </body>
</html>

code/flask webapp/app/templates/dashboard.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>Welcome {{ current_user.username }} </h1>
    <div>Password: {{ current_user.password }} </div>

    <br>
    <br>
    <form action="{{ url_for('auth.logout') }}">
        <input type="submit" class="btn btn-danger" value="Log-out"/>
    </form>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
{% endblock %}

code/flask webapp/app/templates/hello_there.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Testing</title>
  </head>
  <body>
    {%if name %}
    <div>Hello {{name}}</div>

    {% else %}
    <div>Hello stranger</div>
    {% endif %}
  </body>
</html>

code/flask webapp/app/templates/index.html
{% extends "base.html" %}

{% block content %}

  <h1> Welcome to What 2 Watch! </h1>
  <div> Bored? Register and get some movie recommendations! </div>

{% endblock %}

code/flask webapp/app/templates/loading.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Loading</title>
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
        }

        .loader {
            font-size: 24px;
            padding: 20px;
            text-align: center;
            background-color: white;
            border-radius: 4px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }

        .loader::after {
            content: "...";
            animation: dots 1.5s steps(5, end) infinite;
        }

        @keyframes dots {
            0%, 20% { content: "."; }
            40% { content: ".."; }
            60%, 100% { content: "..."; }
        }
    </style>
    <script>
        window.onload = function() {
            fetch('/check_task_status')
                .then(response => response.json())
                .then(data => {
                    if (data.done) {
                        window.location.href = data.redirect_url;
                    } else {
                        setTimeout(() => window.location.reload(), 2000);
                    }
                });
        }
    </script>
</head>
<body>
    <div class="loader">Loading</div>
</body>
</html>

code/flask webapp/app/templates/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container">

        <h1>User Page</h1>
        <br />
        <div class="shadow p-3 mb-5 bg-body rounded">
        <form method="POST">
            {{ form.hidden_tag() }} 
            <div class="form-group">
                {{ form.username.label(class="form-label font-weight-bold") }}
                {{ form.username(class="form-control", style=" height: 40px;") }}
                {% if form.username.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.username.errors %}
                            {{ error }}<br>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-label font-weight-bold") }}
                {{ form.password(class="form-control", style="height: 40px;") }}
                {% if form.password.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.password.errors %}
                            {{ error }}<br>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            
            {{ form.submit(class="btn btn-secondary") }}
        </form>
      </div>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
{% endblock %}

code/flask webapp/app/templates/movie.html
{% extends "base.html" %}
{% block content %}

<style>
    .movie-container {
        display: grid;
        grid-template-columns: repeat(3, 1fr);
        gap: 20px;
        justify-items: center;
    }

    .movie-card {
        background-color: #fff;
        border-radius: 10px;
        box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.2);
        overflow: hidden;
        max-width: 300px;
        text-align: center;
        transition: transform 0.3s ease;
    }

    .movie-card:hover {
        transform: scale(1.05);
    }

    .movie-card img {
        width: 100%;
        height: auto;
        border-bottom: 2px solid #ccc;
    }

    .movie-info {
        padding: 15px;
    }

    .movie-title {
        font-size: 1.2em;
        font-weight: bold;
        margin: 10px 0;
        color: #333;
    }

    .movie-year {
        color: #777;
        font-size: 0.9em;
    }

    .movie-description {
        color: #555;
        font-size: 0.9em;
        margin-top: 10px;
        line-height: 1.4em;
    }

    /* Responsive adjustments */
    @media (max-width: 900px) {
        .movie-container {
            grid-template-columns: repeat(2, 1fr);
        }
    }

    @media (max-width: 600px) {
        .movie-container {
            grid-template-columns: 1fr;
        }
    }

    /* Star rating styling */
    /* Ratings widget */
    .rate {
        display: inline-block;
        border: 0;
    }
    /* Hide radio */
    .rate > input {
        display: none;
    }
    /* Order correctly by floating highest to the right */
    .rate > label {
        float: right;
    }
    /* The star of the show */
    .rate > label:before {
        display: inline-block;
        font-size: 2rem;
        padding: .3rem .2rem;
        margin: 0;
        cursor: pointer;
        font-family: FontAwesome;
        content: "\f005 "; /* full star */
    }

    /* Half star trick */
    .rate .half:before {
        content: "\f089 "; /* half star no outline */
        position: absolute;
        padding-right: 0;
    }
    /* Click + hover color */
    input:checked ~ label, /* color current and previous stars on checked */
    label:hover, label:hover ~ label { color: #f1ce09;  } /* color previous stars on hover */

    /* Hover highlights */
    input:checked + label:hover, input:checked ~ label:hover, /* highlight current and previous stars */
    input:checked ~ label:hover ~ label, /* highlight previous selected stars for new rating */
    label:hover ~ input:checked ~ label /* highlight previous selected stars */ { color: #fdfb6c;  } 

</style>

<div class="movie-container">
    {% for movie in movies %}
    
    {% if movie.img != "None" %}
        <div class="movie-card">
            <img src="{{ movie.img }}" alt="{{movie.img}}">
            <div class="movie-info">
                <div class="movie-title">{{ movie.title }} <span class="movie-year">({{ movie.release_year }})</span></div>
                {% if movie.description != "None" %}
                <div class="movie-description">{{ movie.description }}</div>
                {% endif %}
            </div>

            <form action="/add_rating" method="POST" class="rating-form">
                <fieldset class="rate">
                    <input type="radio" id="rating10-{{movie.movieId}}" name="rating" value="5" {% if movie.rating == 5 %} checked {% endif %}/>
                    <label for="rating10-{{movie.movieId}}" title="5 stars"></label>
                    
                    <input type="radio" id="rating9-{{movie.movieId}}" name="rating" value="4.5" {% if movie.rating == 4.5 %} checked {% endif %}/>
                    <label class="half" for="rating9-{{movie.movieId}}" title="4 1/2 stars"></label>
                    
                    <input type="radio" id="rating8-{{movie.movieId}}" name="rating" value="4" {% if movie.rating == 4 %} checked {% endif %}/>
                    <label for="rating8-{{movie.movieId}}" title="4 stars"></label>
                    
                    <input type="radio" id="rating7-{{movie.movieId}}" name="rating" value="3.5" {% if movie.rating == 3.5 %} checked {% endif %}/>
                    <label class="half" for="rating7-{{movie.movieId}}" title="3 1/2 stars"></label>
                    
                    <input type="radio" id="rating6-{{movie.movieId}}" name="rating" value="3" {% if movie.rating == 3 %} checked {% endif %}/>
                    <label for="rating6-{{movie.movieId}}" title="3 stars"></label>
                    
                    <input type="radio" id="rating5-{{movie.movieId}}" name="rating" value="2.5" {% if movie.rating == 2.5 %} checked {% endif %}/>
                    <label class="half" for="rating5-{{movie.movieId}}" title="2 1/2 stars"></label>
                    
                    <input type="radio" id="rating4-{{movie.movieId}}" name="rating" value="2" {% if movie.rating == 2 %} checked {% endif %}/>
                    <label for="rating4-{{movie.movieId}}" title="2 stars"></label>
                    
                    <input type="radio" id="rating3-{{movie.movieId}}" name="rating" value="1.5" {% if movie.rating == 1.5 %} checked {% endif %}/>
                    <label class="half" for="rating3-{{movie.movieId}}" title="1 1/2 stars"></label>
                    
                    <input type="radio" id="rating2-{{movie.movieId}}" name="rating" value="1" {% if movie.rating == 1 %} checked {% endif %}/>
                    <label for="rating2-{{movie.movieId}}" title="1 star"></label>
                    
                    <input type="radio" id="rating1-{{movie.movieId}}" name="rating" value="0.5" {% if movie.rating == 0.5 %} checked {% endif %}/>
                    <label class="half" for="rating1-{{movie.movieId}}" title="1/2 star"></label>
                </fieldset>
                <input type="hidden" name="movieId" value="{{ movie.movieId }}">
                <input type="hidden" name="query" value="{{ query_info.query }}">
                <input type="hidden" name="moviename" value="{{ movie.moviename }}">
            </form>            
        </div>
        {% endif %}
    {% endfor %}

<br><br>
</div>
{% if query_info.query == "popular" %}
<div class="d-flex justify-content-center my-5">
    <form action="/movies" method="GET" class="load-page-form">
        <button type="submit" class="btn btn-primary btn-lg px-5 rounded-pill shadow-sm" 
                name="p" 
                value="{{ query_info.page_to_load }}">
            Load More
        </button>
        <input type="hidden" name="query" value="{{ query_info.query }}">
    </form>
</div>
{% endif %}

<script>
    document.addEventListener('DOMContentLoaded', function() {
        const forms = document.querySelectorAll('.rating-form');
        forms.forEach(form => {
            const radios = form.querySelectorAll('input[type="radio"]');
            radios.forEach(radio => {
                radio.addEventListener('change', function() {
                    form.submit();
                });
            });
        });
    });
</script>

{% endblock %}

code/flask webapp/app/templates/navbar.html
{% block content %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand text-danger" href="{{ url_for('main.home')}}">What2Watch</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">
          {% if current_user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{{ url_for('movie.movies', query='recommend') }}">Recommendations</a>
          </li>

          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{{ url_for('movie.movies', query='popular') }}">Trending</a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{{ url_for('main.dashboard') }}">Dashboard</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{{ url_for('auth.register') }}">Register</a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{{ url_for('auth.login') }}">Log-in</a>
          </li>
          {% endif %}
        </ul>
        <form class="d-flex" action="/search_movie" method="GET">
          <input class="form-control me-2" type="search" placeholder="Search for a Movie" aria-label="Search" name="searchbar">
          <button class="btn btn-outline-danger" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
{% endblock %}

code/flask webapp/app/templates/register.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
        {% if username %}
        <h1>Hello {{ username }}</h1>
    {% else %}
        <h1>What's your name?</h1>
        <br />
        <div class="shadow p-3 mb-5 bg-body rounded">
        <form method="POST">
            {{ form.hidden_tag() }} 
            <div class="form-group">
                {{ form.username.label(class="form-label font-weight-bold") }}
                {{ form.username(class="form-control", style=" height: 40px;") }}
                {% if form.username.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.username.errors %}
                            {{ error }}<br>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-label font-weight-bold") }}
                {{ form.password(class="form-control", style="height: 40px;") }}
                {% if form.password.errors %}
                    <div class="invalid-feedback d-block">
                        {% for error in form.password.errors %}
                            {{ error }}<br>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            
            {{ form.submit(class="btn btn-secondary") }}
        </form>
      </div>
    {% endif %}
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
{% endblock %}